CC = g++

#Parasail
CFLAGS = -std=c++2a -O3 -Wall -L edlib -lz -lpthread -ledlib -lparasail

all:
	$(CC) FindSimSeqs.cpp $(CFLAGS) -o FindSimSeqs
#	CalcGlobEditDistance
# 	$(CC) CalcGlobEditDistance.cpp $(CFLAGS) -o CalcGlobEditDistance
